name: pdal-sm
channels:
  - conda-forge
dependencies:
  - python>=3.12, <=3.14
  - pip
  - cloudpickle>=3.1.2
  - boto3
  - tiledb>=2.29.2
  - tiledb-py>=0.35.2
  - libpdal-core>=2.9.2
  - python-pdal
  - numpy
  - dask>=2024.11.2
  - pyproj
  - gdal
  - scipy
  - websocket-client
  - python-json-logger
  - dill
  - pandas<3.0.0
  - typing_extensions
  - fast-histogram
