name: silvimetric
channels:
  - conda-forge
dependencies:
  - python
  - tiledb-py
  - python-pdal
  - numpy
  - shapely
  - dask
  - pyproj
  - gdal
  - scipy
  - awscli
  - websocket-client
  - python-json-logger
  - dill
  - pip:
    - line-profiler
