name: pdal-sm
channels:
  - conda-forge
dependencies:
  - python>=3.10, <3.13
  - pip
  # - tiledb-py>=0.32.5
  - boto3
  - tiledb>=2.29.2
  - pdal
  - python-pdal>=3.5.0
  - numpy
  - dask>=2024.11.2
  - pyproj
  - gdal
  - scipy
  - websocket-client
  - python-json-logger
  - dill
  - pandas
  - typing_extensions
  - fast-histogram
  - pip:
    - tiledb>=0.35.2