name: silvimetric
channels:
  - conda-forge
dependencies:
  - python>=3.10, <3.13
  - pip
  # - tiledb-py>=0.32.5
  - boto3
  - pdal
  - python-pdal
  - numpy
  - shapely
  - dask>=2024.11.2
  - pyproj
  - gdal
  - scipy
  - websocket-client
  - python-json-logger
  - dill
  - pandas
  - typing_extensions
  - fast-histogram
  - pip:
    - dask-cloudprovider[aws]
    - git+https://github.com/TileDB-Inc/TileDB-Py